import crafttweaker.api.GenericRecipesManager;
import mods.jei.JEI;
import crafttweaker.api.text.ChatFormatting;


JEI.hideIngredient(<item:exnihilosequentia:andesite_pebble>);
JEI.hideIngredient(<item:exnihilosequentia:basalt_pebble>);
JEI.hideIngredient(<item:exnihilosequentia:blackstone_pebble>);
JEI.hideIngredient(<item:exnihilosequentia:diorite_pebble>);
JEI.hideIngredient(<item:exnihilosequentia:granite_pebble>);
JEI.hideIngredient(<item:exnihilosequentia:stone_pebble>);
JEI.hideIngredient(<item:exnihilosequentia:iron_pieces>);
JEI.hideIngredient(<item:exnihilosequentia:gold_pieces>);
JEI.hideIngredient(<item:exnihilosequentia:copper_pieces>);
JEI.hideIngredient(<item:exnihilosequentia:lead_pieces>);
JEI.hideIngredient(<item:exnihilosequentia:tin_pieces>);
JEI.hideIngredient(<item:exnihilosequentia:uranium_pieces>);
JEI.hideIngredient(<item:exnihilosequentia:platinum_pieces>);
JEI.hideIngredient(<item:exnihilosequentia:silver_pieces>);
JEI.hideIngredient(<item:exnihilosequentia:zinc_pieces>);
JEI.hideIngredient(<item:exnihilosequentia:nickel_pieces>);
JEI.hideIngredient(<item:exnihilosequentia:oak_seeds>);
JEI.hideIngredient(<item:exnihilosequentia:spruce_seeds>);
JEI.hideIngredient(<item:exnihilosequentia:birch_seeds>);
JEI.hideIngredient(<item:exnihilosequentia:blue_coral_larvae>);
JEI.hideIngredient(<item:exnihilosequentia:pink_coral_larvae>);
JEI.hideIngredient(<item:exnihilosequentia:purple_coral_larvae>);
JEI.hideIngredient(<item:exnihilosequentia:red_coral_larvae>);
JEI.hideIngredient(<item:exnihilosequentia:yellow_coral_larvae>);
JEI.hideIngredient(<item:exnihilosequentia:dust>);
JEI.hideIngredient(<item:exnihilosequentia:crushed_netherrack>);
JEI.hideIngredient(<item:exnihilosequentia:crushed_end_stone>);
JEI.hideIngredient(<item:exnihilosequentia:crushed_andesite>);
JEI.hideIngredient(<item:exnihilosequentia:crushed_diorite>);
JEI.hideIngredient(<item:exnihilosequentia:crushed_granite>);
JEI.hideIngredient(<item:exnihilosequentia:blaze_doll>);
JEI.hideIngredient(<item:exnihilosequentia:enderman_doll>);
JEI.hideIngredient(<item:exnihilosequentia:shulker_doll>);
JEI.hideIngredient(<item:exnihilosequentia:guardian_doll>);
JEI.hideIngredient(<item:exnihilosequentia:bee_doll>);
JEI.hideIngredient(<item:exnihilosequentia:diamond_hammer>);
JEI.hideIngredient(<item:exnihilosequentia:golden_hammer>);
JEI.hideIngredient(<item:exnihilosequentia:iron_hammer>);
JEI.hideIngredient(<item:exnihilosequentia:netherite_hammer>);
JEI.hideIngredient(<item:exnihilosequentia:stone_hammer>);
JEI.hideIngredient(<item:exnihilosequentia:wooden_hammer>);
JEI.hideIngredient(<item:exnihilosequentia:acacia_seeds>);
JEI.hideIngredient(<item:exnihilosequentia:jungle_seeds>);
JEI.hideIngredient(<item:exnihilosequentia:end_cake>);
JEI.hideIngredient(<item:exnihilosequentia:jungle_sieve>);
JEI.hideIngredient(<item:exnihilosequentia:oak_sieve>);
JEI.hideIngredient(<item:exnihilosequentia:spruce_sieve>);
JEI.hideIngredient(<item:exnihilosequentia:crimson_sieve>);
JEI.hideIngredient(<item:exnihilosequentia:warped_sieve>);
JEI.hideIngredient(<item:exnihilosequentia:dark_oak_sieve>);
JEI.hideIngredient(<item:exnihilosequentia:birch_sieve>);
JEI.hideIngredient(<item:exnihilosequentia:acacia_sieve>);
JEI.hideIngredient(<item:exnihilosequentia:large_fern_seeds>);
JEI.hideIngredient(<item:exnihilosequentia:string_mesh>);
JEI.hideIngredient(<item:exnihilosequentia:flint_mesh>);
JEI.hideIngredient(<item:exnihilosequentia:iron_mesh>);
JEI.hideIngredient(<item:exnihilosequentia:diamond_mesh>); 
JEI.hideIngredient(<item:exnihilosequentia:emerald_mesh>);
JEI.hideIngredient(<item:exnihilosequentia:netherite_mesh>);
JEI.hideIngredient(<item:exnihilosequentia:fern_seeds>);
JEI.hideIngredient(<item:exnihilosequentia:bamboo_seeds>);
JEI.hideIngredient(<item:exnihilosequentia:pickle_seeds>);
JEI.hideIngredient(<item:exnihilosequentia:kelp_seeds>);
JEI.hideIngredient(<item:exnihilosequentia:sweet_berry_seeds>);
JEI.hideIngredient(<item:exnihilosequentia:potato_seeds>);
JEI.hideIngredient(<item:exnihilosequentia:carrot_seeds>);
JEI.hideIngredient(<item:exnihilosequentia:sugarcane_seeds>);
JEI.hideIngredient(<item:exnihilosequentia:cactus_seeds>);
JEI.hideIngredient(<item:exnihilosequentia:dark_oak_seeds>);
JEI.hideIngredient(<item:exnihilosequentia:mycelium_spores>);
JEI.hideIngredient(<item:exnihilosequentia:grass_seeds>);

JEI.hideIngredient(<item:ae2:facade>);
JEI.hideIngredient(<item:refinedstorage:cover>);
JEI.hideCategory("create:mystery_conversion");
JEI.hideCategory("reliquary:alkahestry_charging");
JEI.hideCategory("reliquary:alkahestry_crafting");

<item:chemlib:element_carbon>.addTooltip("§6Can be used as furnace fuel§r");
<item:chemlib:element_hydrogen>.addTooltip("§6Can be used as furnace fuel§r");
<item:kubejs:new_compound_ethylene>.addTooltip("§3C₂H₄§r");
<item:kubejs:raw_andesite_alloy>.addTooltip("§6§kx§r §4Blood Thirsty§r §6§kx§r");
<item:kubejs:finished_program>.addTooltip("§b§k. §r§bGet back to reality...§r");